### ISSUE TITLE
Site not indexed

### ISSUE THREAD

**Issue by pronskiy** [ThePHPF/thephp.foundation#68]
Unfortunately, there is this thing on all pages right now:
```
<meta name="robots" content="noindex, follow">
```

**Comment by saundefined** [comment]
@pronskiy I just took a quick look:

The `default` layout has `noindex`, and the `page` and `post` have `index`.

That is, the detailed pages of the blog and the CoC page are indexed,
but the rest are not (they extend the `default` layout).

I'd suggest that from the meta tag move the definition of indexing in robots.txt,
or vice versa, write in `default`, that if it is not specified otherwise, then the page is considered indexed.

Thoughts?
